### ISSUE TITLE
migrate to TomographicImaging

### ISSUE THREAD

**Issue by casperdcl** [paskino/conda-package-publish-action#16]
1. scroll to bottom of https://github.com/TomographicImaging/conda-package-publish-action/settings and "Delete this repository" (it's fine to delete this repo since I just created it)
2. scroll to bottom of https://github.com/paskino/conda-package-publish-action/settings and "Transfer ownership" to @TomographicImaging

Things that will keep working after the above:

- CI jobs using the @paskino version will continue working because the repo URL will auto-redirect to @TomographicImaging
- the link to the upstream (https://github.com/maxibor/conda-package-publish-action) will be preserved
- the releases and tags

Things that will break:

- nothing :)

**Comment by paskino** [comment]
Done

https://github.com/TomographicImaging/conda-package-publish-action
